// src/_tests_/Rules.test.jsx
import React from 'react';
import { render, screen } from '@testing-library/react';
import Rules from '../Components/Rules';

describe('Rules Component', () => {
  test('renders the Rules component with the correct text and styles', () => {
    render(<Rules />);
    
    // Check that the component renders with the correct text
    expect(screen.getByText(/How to Play:/i)).toBeInTheDocument();
    expect(screen.getByText(/Enter the run you want to score using button./i)).toBeInTheDocument();
    expect(screen.getByText(/If the number match the number generated by Computer your player is OUT./i)).toBeInTheDocument();
    expect(screen.getByText(/If it does not match then the runs will be added to your score./i)).toBeInTheDocument();
    
  });
});
