/* eslint-disable react/prop-types */
import React from 'react';

export default function Rules() {
  return (
    <div 
      className="flex flex-auto justify-center mx-5 px-1 py-1 my-5 bg-gray-100 text-black font-semibold border-2 border-black rounded-xl"
      style={{
        fontSize: '20px', // Font size
        textAlign: 'center', // Center text horizontally
        display: 'flex', // Enable flexbox
        alignItems: 'center', // Center text vertically
        justifyContent: 'center', 
      }}
    >
      <div>
        How to Play:<br />
        1. Enter the run you want to score using button.<br />
        2. If the number matches the number generated by Computer, your player is OUT.<br />
        3. If it does not match, then the runs will be added to your score.
      </div>
    </div>
  );
}
