// Rules.test.js
import React from 'react';
import { render, screen } from '@testing-library/react';
import Rules from '../Components/Rules';

describe('Rules Component', () => {
  test('renders the rules correctly', () => {
    render(<Rules />); // Render the Rules component

    // Check if the text is present in the document
    expect(screen.getByText(/How to Play:/i)).toBeInTheDocument();
    expect(screen.getByText(/Enter the run you want to score using button./i)).toBeInTheDocument();
    expect(screen.getByText(/If the number matches the number generated by Computer, your player is OUT./i)).toBeInTheDocument();
    expect(screen.getByText(/If it does not match, then the runs will be added to your score./i)).toBeInTheDocument();
  });
});
