export default function Rules(){
    return <div className="flex flex-auto justify-center mx-10 px-4 py-4 my-40 bg-red-700 text-2xl text-black font-semibold border-2 border-white rounded-xl" >
        How to Play:<br/>
        1. Enter the run you want to score using button.<br/>
        2. If the number match the number generated by Computer your player is OUT.<br/>
        3. If it does not match then the runs will be added to your score.
    </div>;
}